name: CI/CD
on:
  workflow_dispatch:
  pull_request:
      types:
        - opened
      branches:
        - "master"

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project        
        run: dotnet build

      - name: Run tests
        run: dotnet test

      - name: Print test success
        if: success()
        run: echo "Tests passed!"
        
      - name: Print test failure
        if: failure()
        run: echo "Tests failed"
